### ISSUE TITLE
Not compatible with most recent jupyter lab

### ISSUE THREAD

**Issue by jbusecke** [mlshapiro/jupyterlab-flake8#4]
I just tried to install the extension using
`jupyter labextension install jupyterlab-flake8`

and get the following error:

```
jupyterlab-flake8-0.1.4.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.3 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.4 <0.17.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.16.3 <0.17.0 @jupyterlab/notebook
>=0.17.2 <0.18.0        >=0.16.3 <0.17.0 @jupyterlab/terminal
```
Is there a workaround available? 

Many thanks.

**Comment by mlshapiro** [comment]
i will fix this shortly - thanks for the note

**Comment by mlshapiro** [comment]
fixed in a89e196301c0d711d70ae300d6a13bbef9aacf19

**Comment by RanFeldeshKik** [comment]
Unfortunately I still get the same error as indicated above by jbusecke when trying to install on JupyterLab 1.0.1
This extension is great !
